version: '3.8'

services:
  db:
    image: postgres:13
    container_name: crypto_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/crypto_data
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["python", "src/api/collect_data.py"]

volumes:
  pgdata:
    driver: local
