version: '3.8'

services:
  schedule:
    build:
      context: .
      dockerfile: src/api/Dockerfile.schedule
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile.api
    ports:
      - "5000:5000"  
    depends_on:
      - db

  dashboard:
    build:
      context: .
      dockerfile: src/api/Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=seu_usuario
      - POSTGRES_PASSWORD=sua_senha
      - POSTGRES_DB=seu_banco
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
