version: '3.8'

services:
  db:
    image: postgres:13  
    container_name: crypto_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: crypto_app
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/crypto_data
    command: python src/api/app.py

volumes:
  pgdata:
    driver: local
